#example of getting new image with changed code
FROM repathdb:latest

ENV DEBIAN_FRONTEND noninteractive

# reinstall RePathDB
COPY RePathDB tmp/RePathDB
COPY setup.py tmp/setup.py
COPY README.md tmp/README.md
COPY mol3d_dash-0.0.1-py3-none-any.whl tmp/mol3d_dash-0.0.1-py3-none-any.whl
# RUN pip3 install -U git+https://github.com/cimm-kzn/CGRtools.git@master#egg=CGRTools[clean2djit,mrv]
RUN cd tmp && pip3 install -U . && rm -rf RePathDB setup.py README.md && cd ..

EXPOSE 5000 7474 5432 7687

ENTRYPOINT ["/opt/boot"]
